# Shiny ui for CCG equity indicators
# 
# Author: Miqdad Asaria
# Date: 30/06/2016
###############################################################################

library(shiny)
library(leaflet)

shinyUI(pageWithSidebar(
			
	# Application title
	headerPanel("CCG Equity Indicators"),
				
	sidebarPanel(
						
	  selectInput("ccg_code", "Select CCG to show details:",
        list("Airedale, Wharfedale and Craven" = "02N",
             "Ashford" = "09C",
             "Aylesbury Vale" = "10Y",
             "Barking and Dagenham" = "07L",
             "Barnet" = "07M",
             "Barnsley" = "02P",
             "Basildon and Brentwood" = "99E",
             "Bassetlaw" = "02Q",
             "Bath and North East Somerset" = "11E",
             "Bedfordshire" = "06F",
             "Bexley" = "07N",
             "Birmingham CrossCity" = "13P",
             "Birmingham South and Central" = "04X",
             "Blackburn with Darwen" = "00Q",
             "Blackpool" = "00R",
             "Bolton" = "00T",
             "Bracknell and Ascot" = "10G",
             "Bradford City" = "02W",
             "Bradford Districts" = "02R",
             "Brent" = "07P",
             "Brighton and Hove" = "09D",
             "Bristol" = "11H",
             "Bromley" = "07Q",
             "Bury" = "00V",
             "Calderdale" = "02T",
             "Cambridgeshire and Peterborough" = "06H",
             "Camden" = "07R",
             "Cannock Chase" = "04Y",
             "Canterbury and Coastal" = "09E",
             "Castle Point and Rochford" = "99F",
             "Central London (Westminster)" = "09A",
             "Central Manchester" = "00W",
             "Chiltern" = "10H",
             "Chorley and South Ribble" = "00X",
             "City and Hackney" = "07T",
             "Coastal West Sussex" = "09G",
             "Corby" = "03V",
             "Coventry and Rugby" = "05A",
             "Crawley" = "09H",
             "Croydon" = "07V",
             "Cumbria" = "01H",
             "Darlington" = "00C",
             "Dartford, Gravesham and Swanley" = "09J",
             "Doncaster" = "02X",
             "Dorset" = "11J",
             "Dudley" = "05C",
             "Durham Dales, Easington and Sedgefield" = "00D",
             "Ealing" = "07W",
             "East and North Hertfordshire" = "06K",
             "East Lancashire" = "01A",
             "East Leicestershire and Rutland" = "03W",
             "East Riding of Yorkshire" = "02Y",
             "East Staffordshire" = "05D",
             "East Surrey" = "09L",
             "Eastbourne, Hailsham and Seaford" = "09F",
             "Eastern Cheshire" = "01C",
             "Enfield" = "07X",
             "Erewash" = "03X",
             "Fareham and Gosport" = "10K",
             "Fylde & Wyre" = "02M",
             "Gloucestershire" = "11M",
             "Great Yarmouth and Waveney" = "06M",
             "Greater Huddersfield" = "03A",
             "Greater Preston" = "01E",
             "Greenwich" = "08A",
             "Guildford and Waverley" = "09N",
             "Halton" = "01F",
             "Hambleton, Richmondshire and Whitby" = "03D",
             "Hammersmith and Fulham" = "08C",
             "Hardwick" = "03Y",
             "Haringey" = "08D",
             "Harrogate and Rural District" = "03E",
             "Harrow" = "08E",
             "Hartlepool and Stockton-on-Tees" = "00K",
             "Hastings and Rother" = "09P",
             "Havering" = "08F",
             "Herefordshire" = "05F",
             "Herts Valleys" = "06N",
             "Heywood, Middleton and Rochdale" = "01D",
             "High Weald Lewes Havens" = "99K",
             "Hillingdon" = "08G",
             "Horsham and Mid Sussex" = "09X",
             "Hounslow" = "07Y",
             "Hull" = "03F",
             "Ipswich and East Suffolk" = "06L",
             "Isle of Wight" = "10L",
             "Islington" = "08H",
             "Kernow" = "11N",
             "Kingston" = "08J",
             "Knowsley" = "01J",
             "Lambeth" = "08K",
             "Lancashire North" = "01K",
             "Leeds North" = "02V",
             "Leeds South and East" = "03G",
             "Leeds West" = "03C",
             "Leicester City" = "04C",
             "Lewisham" = "08L",
             "Lincolnshire East" = "03T",
             "Lincolnshire West" = "04D",
             "Liverpool" = "99A",
             "Luton" = "06P",
             "Mansfield and Ashfield" = "04E",
             "Medway" = "09W",
             "Merton" = "08R",
             "Mid Essex" = "06Q",
             "Milton Keynes" = "04F",
             "Nene" = "04G",
             "Newark & Sherwood" = "04H",
             "Newbury and District" = "10M",
             "Newcastle Gateshead" = "13T",
             "Newham" = "08M",
             "North & West Reading" = "10N",
             "North Derbyshire" = "04J",
             "North Durham" = "00J",
             "North East Essex" = "06T",
             "North East Hampshire and Farnham" = "99M",
             "North East Lincolnshire" = "03H",
             "North Hampshire" = "10J",
             "North Kirklees" = "03J",
             "North Lincolnshire" = "03K",
             "North Manchester" = "01M",
             "North Norfolk" = "06V",
             "North Somerset" = "11T",
             "North Staffordshire" = "05G",
             "North Tyneside" = "99C",
             "North West Surrey" = "09Y",
             "Northern, Eastern and Western Devon" = "99P",
             "Northumberland" = "00L",
             "Norwich" = "06W",
             "Nottingham City" = "04K",
             "Nottingham North and East" = "04L",
             "Nottingham West" = "04M",
             "Oldham" = "00Y",
             "Oxfordshire" = "10Q",
             "Portsmouth" = "10R",
             "Redbridge" = "08N",
             "Redditch and Bromsgrove" = "05J",
             "Richmond" = "08P",
             "Rotherham" = "03L",
             "Rushcliffe" = "04N",
             "Salford" = "01G",
             "Sandwell and West Birmingham" = "05L",
             "Scarborough and Ryedale" = "03M",
             "Sheffield" = "03N",
             "Shropshire" = "05N",
             "Slough" = "10T",
             "Solihull" = "05P",
             "Somerset" = "11X",
             "South Cheshire" = "01R",
             "South Devon and Torbay" = "99Q",
             "South East Staffordshire and Seisdon Peninsula" = "05Q",
             "South Eastern Hampshire" = "10V",
             "South Gloucestershire" = "12A",
             "South Kent Coast" = "10A",
             "South Lincolnshire" = "99D",
             "South Manchester" = "01N",
             "South Norfolk" = "06Y",
             "South Reading" = "10W",
             "South Sefton" = "01T",
             "South Tees" = "00M",
             "South Tyneside" = "00N",
             "South Warwickshire" = "05R",
             "South West Lincolnshire" = "04Q",
             "South Worcestershire" = "05T",
             "Southampton" = "10X",
             "Southend" = "99G",
             "Southern Derbyshire" = "04R",
             "Southport and Formby" = "01V",
             "Southwark" = "08Q",
             "St Helens" = "01X",
             "Stafford and Surrounds" = "05V",
             "Stockport" = "01W",
             "Stoke on Trent" = "05W",
             "Sunderland" = "00P",
             "Surrey Downs" = "99H",
             "Surrey Heath" = "10C",
             "Sutton" = "08T",
             "Swale" = "10D",
             "Swindon" = "12D",
             "Tameside and Glossop" = "01Y",
             "Telford and Wrekin" = "05X",
             "Thanet" = "10E",
             "Thurrock" = "07G",
             "Tower Hamlets" = "08V",
             "Trafford" = "02A",
             "Vale of York" = "03Q",
             "Vale Royal" = "02D",
             "Wakefield" = "03R",
             "Walsall" = "05Y",
             "Waltham Forest" = "08W",
             "Wandsworth" = "08X",
             "Warrington" = "02E",
             "Warwickshire North" = "05H",
             "West Cheshire" = "02F",
             "West Essex" = "07H",
             "West Hampshire" = "11A",
             "West Kent" = "99J",
             "West Lancashire" = "02G",
             "West Leicestershire" = "04V",
             "West London" = "08Y",
             "West Norfolk" = "07J",
             "West Suffolk" = "07K",
             "Wigan Borough" = "02H",
             "Wiltshire" = "99N",
             "Windsor, Ascot and Maidenhead" = "11C",
             "Wirral" = "12F",
             "Wokingham" = "11D",
             "Wolverhampton" = "06A",
             "Wyre Forest" = "06D"), selected="03Q"),
				
	    selectInput("trim", "Trim outliers on scatter plots:",
	            list("True" = "TRUE",
	                 "False" = "FALSE"), selected="TRUE")),
	
	                 
	mainPanel(
	      h3(textOutput("title")),
	      h3(textOutput("ccg")),
	      tabsetPanel(
				  tabPanel("Scatter", plotOutput("scatter_plot")),
				  tabPanel("Caterpillar", plotOutput("caterpillar_plot")),
				  tabPanel("Map", leafletOutput("ccg_map")),
				  tabPanel("Similar CCGs", dataTableOutput("similar_agi_data")),
				  tabPanel("All CCGs", dataTableOutput("ccg_agi_data"))
				)
					
		)
))